import { SignIn, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton} from "@clerk/nextjs";
import { SignOutButton} from "@clerk/nextjs";

const CreatePostWizard = () =>{
  const {user} = useUser();
  if(!user) return null;
  return (
    <div className="flex w-full gap-3"> <img src={user.imageUrl} 
    alt = "Profile image" 
    className="w-11 h-11 rounded-full"
    />
    <input placeholder="type something..." className = "bg-transparent text-white"/>
    </div>
  );
}

export default function Home() {
  const {data, isLoading} = api.posts.getAll.useQuery();

  const user = useUser();
 
  if (isLoading) return <div>Loading...</div>
  if(!data) return <div>Oops! Something went wrong...</div>
 
  return (
    < >
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center bg-gradient-to-b from-purple-500 to-blue-900 ">
        <div className= "w-full border-x border-blue-900 md:max-w-2xl">
        <div className = "border-blue-900 border-b p-4 flex"> 
            {user.isSignedIn && <CreatePostWizard/>}
        
            {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
        </div>
        <div>
          {[...data!,...data!]?.map((post) => (<div key = {post.id} className="p-8 border-b border-blue-900">{post.content}</div>))}
        </div>
        </div> 
      </main>
    </>
  );
}
